name: dvm
description: "DVM - Dementia Virtual Memory App: Helping users preserve and manage memories."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  firebase_core: ^4.0.0
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  http: ^1.5.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  characters: ^1.4.0
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  cloudinary_public: ^0.23.1
  onesignal_flutter: ^5.3.4
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  file_picker: ^10.3.3
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_gemini: ^3.0.0
  flutter_dotenv: ^6.0.0
  confetti: ^0.8.0
  flutter_isolate: ^2.1.0
  foundation: ^0.0.5
  image: ^4.5.4
  typed_data: ^1.4.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/